In [3]:
import pandas as pd
from urllib.parse import urlparse
import re

In [4]:
df=pd.read_csv(r'E:\UNMC Internship Document\Github Upload\data\dataset_live_links_v2.csv')

In [5]:
df.head()

                                             url  label
0                       https://www.icecream.com      0
1  https://proud-lake-5717.kx7hcssq.workers.dev/      1
2                         https://www.stmusic.at      0
3               http://icuwtzw.cloudaccess.host/      1
4                  http://bcc56.freehostpro.com/      1

In [6]:
df['label'].value_counts()

label
1    441
0    363
Name: count, dtype: int64

In [7]:
def get_url_length(url):
    return len(url)

def get_has_https(url):
    return 1 if urlparse(url).scheme=="https" else 0

def get_num_subdomains(url):
    host=urlparse(url).netloc
    if host == "":
        return 0
    else:
        return host.count(".")-1

In [8]:
test=df.loc[1,'url']
test

'https://proud-lake-5717.kx7hcssq.workers.dev/'

In [9]:
print("Length:", get_url_length(test))
print(f"Has HTTPS: {get_has_https}")
print(f"Number of Subdomains: {get_num_subdomains(test)}")

Length: 45
Has HTTPS: <function get_has_https at 0x000002CCE9E67D80>
Number of Subdomains: 2

In [10]:
df['url_length']=df['url'].apply(get_url_length)
df['has_https']=df['url'].apply(get_has_https)
df['num_subdomains']=df['url'].apply(get_num_subdomains)

df.head()

,url,label,url_length,has_https,num_subdomains
0,https://www.icecream.com,0,24,1,1
1,https://proud-lake-5717.kx7hcssq.workers.dev/,1,45,1,2
2,https://www.stmusic.at,0,22,1,1
3,http://icuwtzw.cloudaccess.host/,1,32,0,1
4,http://bcc56.freehostpro.com/,1,29,0,1

In [11]:
def get_special_char_count(url):
    #count every character that is NOT a letter or digit
    return len(re.findall(r"[^a-zA-z0-9]",url))

def get_suspicious_keyword_count(url):
    #count how many scam-related urgency driven words appear in the url
    pattern=r"donate|urgent|help|verify|secure|account|login|gift|fund|claim"
    return len(re.findall(pattern, url.lower()))

In [12]:
test=df.loc[1,'url']
print("URL:",test)
print("Special chars:",get_special_char_count(test))
print("Suspicioius keywords:",get_suspicious_keyword_count(test))

URL: https://proud-lake-5717.kx7hcssq.workers.dev/
Special chars: 9
Suspicioius keywords: 0

In [13]:
df['Special Character Count']=df['url'].apply(get_special_char_count)
df['Suspicious Keyword Count']=df['url'].apply(get_suspicious_keyword_count)


df.head()

,url,label,url_length,has_https,num_subdomains,Special Character Count,Suspicious Keyword Count
0,https://www.icecream.com,0,24,1,1,5,0
1,https://proud-lake-5717.kx7hcssq.workers.dev/,1,45,1,2,9,0
2,https://www.stmusic.at,0,22,1,1,5,0
3,http://icuwtzw.cloudaccess.host/,1,32,0,1,6,0
4,http://bcc56.freehostpro.com/,1,29,0,1,6,0